import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
process.env.PLAYWRIGHT_BROWSERS_PATH ??= path.join(root, ".pw-browsers");
const { chromium } = await import("playwright");
const evidence = process.env.REASONIX_MAINTENANCE_EVIDENCE ?? "/tmp/reasonix-maintenance-submit-evidence";
const server = await createServer({ root, logLevel: "error", server: { host: "127.0.0.1", port: 0 } });
await server.listen();
let browser;
let page;
try {
  browser = await chromium.launch({ headless: true });
  page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  page.setDefaultTimeout(15000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/bench/maintenance-submit.html?mock=1`);
  await page.waitForFunction(() => Boolean(window.maintenanceProbe));
  const input = page.locator("textarea").first();
  await page.evaluate(() => window.maintenanceProbe.holdAdmission());
  await input.fill("/compact");
  await input.press("Enter");
  await page.locator(".composer-run-strip__state").filter({ hasText: "Preparing compaction" }).waitFor();
  assert.equal(await page.locator(".composer-run-strip__metrics").count(), 0);
  await input.fill("Next message draft");
  assert.match(await page.locator(".composer-run-strip__state").innerText(), /Preparing compaction/);
  await page.getByRole("button", { name: "Switch session" }).click();
  assert.equal(await page.locator(".composer-run-strip__state").count(), 0);
  await input.fill("Session B draft");
  await page.getByRole("button", { name: "Switch session" }).click();
  assert.equal(await input.inputValue(), "Next message draft");
  assert.match(await page.locator(".composer-run-strip__state").innerText(), /Preparing compaction/);
  await page.getByRole("button", { name: "Switch session" }).click();
  await page.evaluate(() => window.maintenanceProbe.releaseAdmission());
  await page.waitForFunction(() => window.maintenanceProbe.stats().starts === 1);
  assert.equal(await page.locator(".composer-run-strip__state").count(), 0, "background admission must not change session B's submission state");
  assert.equal(await input.inputValue(), "Session B draft");
  await page.getByRole("button", { name: "Switch session" }).click();
  assert.equal(await input.inputValue(), "Next message draft", "admission must preserve edits made while submitting");
  await page.locator(".compaction__spinner").waitFor();
  assert.match(await page.locator(".compaction--pending").innerText(), /Generating summary/);
  assert.equal(await page.locator(".compaction--pending").getAttribute("role"), "status");
  await page.locator(".composer-run-strip__state").filter({ hasText: "Compacting conversation" }).waitFor();
  assert.equal(await page.locator(".composer-run-strip__metrics").count(), 0);
  assert.equal(await page.locator(".compaction__spinner").evaluate(element => getComputedStyle(element).animationName), "spin");
  await page.emulateMedia({ reducedMotion: "reduce" });
  assert.equal(await page.locator(".compaction__spinner").evaluate(element => getComputedStyle(element).animationName), "none");
  await page.emulateMedia({ reducedMotion: "no-preference" });
  for (const command of ["/compact", "/compact keep decisions"]) {
    await input.fill(command);
    await input.press("Enter");
    await page.waitForFunction(() => document.querySelector("textarea").value === "", null, { timeout: 15000 });
  }
  assert.deepEqual(await page.evaluate(() => window.maintenanceProbe.stats()), { starts: 1, submissions: 3 }, "known-running duplicate uses management admission rather than the follow-up queue");
  assert.equal(await page.locator(".compaction").count(), 1);
  assert.match(await page.locator("body").innerText(), /already in progress/);
  assert.equal(await page.locator(".msg__send-failed").count(), 0);
  // Exercise the production paste folding handler without touching the user's clipboard.
  const focus = "preserve architecture decisions\n".repeat(100);
  await input.fill("/compact ");
  await input.evaluate((element, text) => {
    const data = new DataTransfer(); data.setData("text/plain", text);
    element.dispatchEvent(new ClipboardEvent("paste", { bubbles: true, cancelable: true, clipboardData: data }));
  }, focus);
  assert.match(await input.inputValue(), /Pasted/);
  await input.press("Enter");
  await page.waitForFunction(() => window.maintenanceProbe.stats().submissions === 4);
  assert.deepEqual(await page.evaluate(() => window.maintenanceProbe.stats()), { starts: 1, submissions: 4 });
  assert.ok((await page.evaluate(() => window.maintenanceProbe.lastInput())).includes(focus));
  assert.equal(await page.locator(".msg__send-failed").count(), 0);
  await mkdir(evidence, { recursive: true });
  await page.screenshot({ path: path.join(evidence, "duplicate-compact.png") });
  await page.getByRole("button", { name: "Switch session" }).click();
  assert.equal(await page.locator("[data-active-session]").innerText(), "B");
  await page.evaluate(() => window.maintenanceProbe.complete());
  assert.equal(await page.locator(".compaction").count(), 0, "background completion cannot appear in another session");
  await page.getByRole("button", { name: "Switch session" }).click();
  await page.locator(".compaction button").click();
  assert.match(await page.locator(".compaction").innerText(), /durable compaction summary/);
  assert.deepEqual(await page.evaluate(() => window.maintenanceProbe.lifecycle()), { running: false, cancellable: false, echoes: 0 });
  await page.evaluate(() => window.maintenanceProbe.coldRestore());
  assert.equal(await page.locator(".compaction").count(), 1);
  const disclosure = page.locator(".compaction button");
  if (await disclosure.getAttribute("aria-expanded") === "false") await disclosure.click();
  assert.match(await page.locator(".compaction").innerText(), /durable compaction summary/);
  await page.screenshot({ path: path.join(evidence, "restored-summary.png") });
  await page.evaluate(() => window.maintenanceProbe.holdAdmission());
  await input.fill("/compact");
  await input.press("Enter");
  await page.locator(".composer-run-strip__state").filter({ hasText: "Preparing compaction" }).waitFor();
  await input.fill("Keep this draft after failure");
  await page.evaluate(() => window.maintenanceProbe.rejectAdmission());
  await page.locator(".composer-run-strip__state").waitFor({ state: "detached" });
  assert.equal(await input.inputValue(), "Keep this draft after failure");
  await page.evaluate(() => window.maintenanceProbe.holdAdmission());
  await input.fill("Ordinary request");
  await input.press("Enter");
  await page.waitForFunction(() => window.maintenanceProbe.stats().submissions === 6);
  await input.fill("/compact");
  assert.equal(await page.locator(".composer-run-strip__state").count(), 0, "editing a normal submission into /compact cannot relabel the in-flight request");
  await page.evaluate(() => window.maintenanceProbe.rejectAdmission());
  await page.getByRole("button", { name: "Send (Enter)", exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log(`PASS submission edits, session isolation, admission failure, duplicate compaction and durable summary restore; evidence: ${evidence}`);
} catch (error) {
  await mkdir(evidence, { recursive: true });
  await page?.screenshot({ path: path.join(evidence, "failure.png") });
  console.error(await page?.evaluate(() => ({ stats: window.maintenanceProbe?.stats(), text: document.body.innerText.slice(-2500) })));
  throw error;
} finally {
  await browser?.close();
  await server.close();
}
