import { useController } from "../lib/useController";

/**
 * Narrows the legacy controller into explicit App-facing runtime ports.
 * It does not own state: Controller stores remain authoritative and every
 * source-bound operation still executes through the existing controller.
 */
export function useAppRuntimeAdapter() {
  const controller = useController();
  return {
    snapshot: {
      state: controller.state,
      liveStore: controller.liveStore,
      activeTabId: controller.activeTabId,
      notice: controller.notice,
    },
    composer: {
      sendToTab: controller.sendToTab,
      runShellForTab: controller.runShellForTab,
      steerForTab: controller.steerForTab,
      cancel: controller.cancel,
      cancelForTab: controller.cancelForTab,
      setControllerMode: controller.setControllerMode,
      setControllerModeForTab: controller.setControllerModeForTab,
      setCollaborationMode: controller.setCollaborationMode,
      setCollaborationModeForTab: controller.setCollaborationModeForTab,
      setToolApprovalMode: controller.setToolApprovalMode,
      setToolApprovalModeForTab: controller.setToolApprovalModeForTab,
      setComposerProfileForTab: controller.setComposerProfileForTab,
      setGoalForTab: controller.setGoalForTab,
      editGoalForTab: controller.editGoalForTab,
      resumeGoalForTab: controller.resumeGoalForTab,
      pauseGoalForTab: controller.pauseGoalForTab,
      clearGoal: controller.clearGoal,
      clearGoalForTab: controller.clearGoalForTab,
      setModel: controller.setModel,
      setModelForTab: controller.setModelForTab,
      setEffort: controller.setEffort,
      setEffortForTab: controller.setEffortForTab,
      cancelJob: controller.cancelJob,
    },
    sessionActions: {
      isPromptCurrentForTab: controller.isPromptCurrentForTab,
      recoverDeliveryToTab: controller.recoverDeliveryToTab,
      approveForTab: controller.approveForTab,
      resolvePlanDecisionForTab: controller.resolvePlanDecisionForTab,
      resolveRecoveryForTab: controller.resolveRecoveryForTab,
      answerQuestionForTab: controller.answerQuestionForTab,
      answerMCPInteractionForTab: controller.answerMCPInteractionForTab,
      dismissExtensionForm: controller.dismissExtensionForm,
      drainExtensionNotifications: controller.drainExtensionNotifications,
      clearSession: controller.clearSession,
      newSession: controller.newSession,
      listSessions: controller.listSessions,
      listTrashedSessions: controller.listTrashedSessions,
      resumeSession: controller.resumeSession,
      openChannelSession: controller.openChannelSession,
      previewSession: controller.previewSession,
      deleteSession: controller.deleteSession,
      restoreSession: controller.restoreSession,
      purgeTrashedSession: controller.purgeTrashedSession,
      renameSession: controller.renameSession,
      loadOlderHistory: controller.loadOlderHistory,
      loadNewerHistory: controller.loadNewerHistory,
      navigateToTurn: controller.navigateToTurn,
      retrySessionHistory: controller.retrySessionHistory,
      rewindForTab: controller.rewindForTab,
      rewindForTabDetailed: controller.rewindForTabDetailed,
      undoRewindForTab: controller.undoRewindForTab,
      forkTurnForTab: controller.forkTurnForTab,
    },
    workspace: {
      refreshMeta: controller.refreshMeta,
      pickWorkspace: controller.pickWorkspace,
      switchWorkspace: controller.switchWorkspace,
    },
    navigation: {
      switchTab: controller.switchTab,
      switchRemoteTab: controller.switchRemoteTab,
      createIsolatedWorktree: controller.createIsolatedWorktree,
      closeTab: controller.closeTab,
      reorderTabs: controller.reorderTabs,
      activateTopic: controller.activateTopic,
      openCanonicalSession: controller.openCanonicalSession,
      noteNavigationIntent: controller.noteNavigationIntent,
      currentNavigationIntent: controller.currentNavigationIntent,
      registeredNavigationIntent: controller.registeredNavigationIntent,
      isNavigationIntentCurrent: controller.isNavigationIntentCurrent,
      reassertVisibleTabAfterStaleNavigation: controller.reassertVisibleTabAfterStaleNavigation,
      syncActiveTab: controller.syncActiveTab,
      ensureBlankSurface: controller.ensureBlankSurface,
      commitSingleSurfaceNavigation: controller.commitSingleSurfaceNavigation,
    },
  };
}
