package hostrpc

import (
	"fmt"
	"strings"
	"testing"
)

type tsOther struct {
	Name string `json:"name"`
}

type tsRecord struct {
	Label   string            `json:"label"`
	Weird   string            `json:"content-type"`
	Next    *tsRecord         `json:"next"`
	Tags    []string          `json:"tags,omitempty"`
	Owners  []*tsOther        `json:"owners"`
	Extra   map[string]any    `json:"extra"`
	Payload any               `json:"payload"`
	Nested  struct{ On bool } `json:"nested"`
}

type tsTarget struct{}

func (*tsTarget) Version() string                               { return "" }
func (*tsTarget) Reset()                                        {}
func (*tsTarget) Save(r tsRecord, force bool) (tsRecord, error) { return r, nil }
func (*tsTarget) List() ([]tsRecord, error)                     { return nil, nil }
func (*tsTarget) Others() map[string][]tsOther                  { return nil }

func TestWriteTypeScriptEmitsContractDeclarations(t *testing.T) {
	c := Build(mustRegistry(t, &tsTarget{}, nil), []string{"agent:event", "runtime:rebuilt"})
	var b strings.Builder
	if err := WriteTypeScript(&b, c); err != nil {
		t.Fatal(err)
	}
	out := b.String()
	if !strings.HasPrefix(out, "// Code generated by go run . -emit-contract; DO NOT EDIT.\n") {
		t.Fatalf("header = %.80q", out)
	}
	for _, want := range []string{
		fmt.Sprintf("export const DESKTOP_PROTOCOL_VERSION = %d;", ProtocolVersion),
		`export const DESKTOP_CONTRACT_DIGEST = "` + c.Digest() + `";`,
		"export const DESKTOP_COMMANDS = [\n  \"List\",\n  \"Others\",\n  \"Reset\",\n  \"Save\",\n  \"Version\",\n] as const;",
		"export const DESKTOP_EVENTS = [\n  \"agent:event\",\n  \"runtime:rebuilt\",\n] as const;",
		"export type DesktopCommandName = (typeof DESKTOP_COMMANDS)[number];",
		"export interface tsOther {\n  name: string;\n}",
		"export interface tsRecord {\n",
		"  label: string;\n",
		"  \"content-type\": string;\n",
		"  next?: tsRecord | null;\n",
		"  tags?: string[];\n",
		"  owners: (tsOther | null)[];\n",
		"  extra: Record<string, unknown>;\n",
		"  payload: unknown;\n",
		"  nested: tsRecord_Nested;\n",
		"export interface tsRecord_Nested {\n  On: boolean;\n}",
		"export interface GeneratedDesktopCommands {\n",
		"  List(): Promise<tsRecord[]>;\n",
		"  Others(): Promise<Record<string, tsOther[]>>;\n",
		"  Reset(): Promise<void>;\n",
		"  Save(arg0: tsRecord, arg1: boolean): Promise<tsRecord>;\n",
		"  Version(): Promise<string>;\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output lacks %q\n%s", want, out)
		}
	}
}

func TestTypeScriptNamesDisambiguateCollisions(t *testing.T) {
	names := tsTypeNames(map[string]ObjectType{
		"main.Item":        {},
		"taskmonitor.Item": {},
		"main.Solo":        {},
		"main.Box[int]":    {},
	})
	want := map[string]string{
		"main.Item":        "main_Item",
		"taskmonitor.Item": "taskmonitor_Item",
		"main.Solo":        "Solo",
		"main.Box[int]":    "Box_int_",
	}
	for key, name := range want {
		if names[key] != name {
			t.Errorf("%s -> %q, want %q", key, names[key], name)
		}
	}
}

func TestTypeScriptNamesDoNotShadowGeneratedHelpers(t *testing.T) {
	names := tsTypeNames(map[string]ObjectType{
		"transcript.Record": {}, "main.Promise": {}, "main.GeneratedDesktopCommands": {},
	})
	for key, want := range map[string]string{
		"transcript.Record": "transcript_Record", "main.Promise": "main_Promise",
		"main.GeneratedDesktopCommands": "main_GeneratedDesktopCommands",
	} {
		if names[key] != want {
			t.Errorf("%s = %s, want %s", key, names[key], want)
		}
	}
}
