package hostrpc

import (
	"encoding/json"
	"fmt"
	"io"
	"maps"
	"regexp"
	"slices"
	"strings"
)

var tsIdentifierRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// WriteTypeScript renders c as desktopContract.generated.ts: the digest and
// command/event tables the shell embeds plus one interface per DTO and the
// GeneratedDesktopCommands method table the renderer bridge implements.
func WriteTypeScript(w io.Writer, c Contract) error {
	names := tsTypeNames(c.Types)
	var b strings.Builder
	b.WriteString("// Code generated by go run . -emit-contract; DO NOT EDIT.\n")
	b.WriteString("/* eslint-disable */\n\n")
	fmt.Fprintf(&b, "export const DESKTOP_PROTOCOL_VERSION = %d;\n\n", c.ProtocolVersion)
	fmt.Fprintf(&b, "export const DESKTOP_CONTRACT_DIGEST = %s;\n\n", tsString(c.Digest()))

	commandNames := make([]string, 0, len(c.Commands))
	for _, cmd := range c.Commands {
		commandNames = append(commandNames, cmd.Name)
	}
	slices.Sort(commandNames)
	writeStringTable(&b, "DESKTOP_COMMANDS", commandNames)
	writeStringTable(&b, "DESKTOP_EVENTS", c.Events)
	b.WriteString("export type DesktopCommandName = (typeof DESKTOP_COMMANDS)[number];\n\n")
	b.WriteString("export type DesktopEventName = (typeof DESKTOP_EVENTS)[number];\n\n")

	for _, key := range slices.Sorted(maps.Keys(c.Types)) {
		fmt.Fprintf(&b, "export interface %s {\n", names[key])
		for _, f := range c.Types[key].Fields {
			optional := ""
			if f.Optional {
				optional = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", tsProperty(f.Name), optional, tsType(f.Type, names))
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("export interface GeneratedDesktopCommands {\n")
	for _, cmd := range c.Commands {
		params := make([]string, 0, len(cmd.Params))
		for i, p := range cmd.Params {
			params = append(params, fmt.Sprintf("arg%d: %s", i, tsType(p, names)))
		}
		result := "void"
		if cmd.Result != nil {
			result = tsType(*cmd.Result, names)
		}
		fmt.Fprintf(&b, "  %s(%s): Promise<%s>;\n", cmd.Name, strings.Join(params, ", "), result)
	}
	b.WriteString("}\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func writeStringTable(b *strings.Builder, name string, values []string) {
	fmt.Fprintf(b, "export const %s = [\n", name)
	for _, v := range values {
		fmt.Fprintf(b, "  %s,\n", tsString(v))
	}
	b.WriteString("] as const;\n\n")
}

func tsType(t TypeRef, names map[string]string) string {
	switch t.Kind {
	case KindString:
		return "string"
	case KindNumber, KindInteger:
		return "number"
	case KindBoolean:
		return "boolean"
	case KindArray:
		elem := tsType(*t.Elem, names)
		if strings.Contains(elem, " | ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]"
	case KindMap:
		return "Record<string, " + tsType(*t.Elem, names) + ">"
	case KindObject:
		if name, ok := names[t.Ref]; ok {
			return name
		}
		return tsIdentifier(t.Ref)
	case KindNullable:
		return tsType(*t.Elem, names) + " | null"
	}
	return "unknown"
}

// tsTypeNames maps each pkg.Name key to a TypeScript interface name: the
// bare Go name when unique, otherwise prefixed with its package.
func tsTypeNames(types map[string]ObjectType) map[string]string {
	bare := map[string][]string{}
	for key := range types {
		_, name, _ := strings.Cut(key, ".")
		bare[name] = append(bare[name], key)
	}
	out := make(map[string]string, len(types))
	for name, ks := range bare {
		// These names belong to the emitted module or its generic helpers.
		// A DTO named Record must not shadow Record<string, T> elsewhere.
		reserved := name == "Record" || name == "Promise" || name == "GeneratedDesktopCommands" ||
			name == "DesktopCommandName" || name == "DesktopEventName"
		for _, key := range ks {
			if len(ks) == 1 && !reserved {
				out[key] = tsIdentifier(name)
				continue
			}
			out[key] = tsIdentifier(strings.ReplaceAll(key, ".", "_"))
		}
	}
	return out
}

func tsIdentifier(name string) string {
	var b strings.Builder
	for i, r := range name {
		switch {
		case r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

func tsProperty(name string) string {
	if tsIdentifierRe.MatchString(name) {
		return name
	}
	return tsString(name)
}

func tsString(s string) string {
	quoted, _ := json.Marshal(s)
	return string(quoted)
}
