import {JSDOM} from 'jsdom';
import React,{act} from 'react';
import assert from 'node:assert/strict';
import {LocaleProvider} from '../lib/i18n';
const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost',pretendToBeVisual:true});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,requestAnimationFrame:dom.window.requestAnimationFrame.bind(dom.window),IS_REACT_ACT_ENVIRONMENT:true});
const {createRoot}=await import('react-dom/client');
const {ConnectionTitle}=await import('../components/ConnectionTitle');
const root=createRoot(document.getElementById('root')!);
let calls=0, success=false;
await act(async()=>root.render(<LocaleProvider><ConnectionTitle label="My connection" busy={false} onSave={async label=>{assert.equal(label,'My connection');calls++;return success;}}/></LocaleProvider>));
await act(async()=>document.querySelector('button')!.click());
assert.ok(document.querySelector('input'));
await act(async()=>document.querySelector('input')!.dispatchEvent(new dom.window.FocusEvent('blur',{bubbles:true})));
assert.equal(calls,0);
await act(async()=>document.querySelector('input')!.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
assert.equal(document.querySelector('input'),null);assert.equal(calls,0);
await act(async()=>document.querySelector('button')!.click());
await act(async()=>document.querySelector('input')!.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true})));
assert.equal(calls,1);assert.ok(document.querySelector('[role="alert"]'));assert.equal(document.querySelector('input')!.value,'My connection');
success=true;
await act(async()=> (document.querySelector('.connection-title-editor__row button') as HTMLButtonElement).click());
assert.equal(calls,2);assert.equal(document.querySelector('input'),null);
await act(async()=>root.unmount());
console.log('PASS: explicit save, Escape cancel, no blur submission, failed save retains draft, retry closes editor');
