import { JSDOM } from 'jsdom';
import React, {act} from 'react';
import assert from 'node:assert/strict';
const dom = new JSDOM('<div id="root"></div>', {url:'http://localhost',pretendToBeVisual:true});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,Node:dom.window.Node,HTMLElement:dom.window.HTMLElement,requestAnimationFrame:dom.window.requestAnimationFrame.bind(dom.window),cancelAnimationFrame:dom.window.cancelAnimationFrame.bind(dom.window),IS_REACT_ACT_ENVIRONMENT:true});
window.matchMedia = (()=>({matches:true,addEventListener(){},removeEventListener(){}})) as any;
const {createRoot}=await import('react-dom/client');
const {ModelPicker}=await import('../components/SettingsPanel');
const {LocaleProvider}=await import('../lib/i18n');
const root=createRoot(document.getElementById('root')!);
let selected='';
const providers=['one','two'].map(name=>({name,displayName:`Connection ${name}`,kind:'openai',models:['shared-model'],keySet:true,apiKeyEnv:'KEY',builtIn:true}));
await act(async()=>root.render(<LocaleProvider><ModelPicker s={{providers} as any} refs={['one/shared-model','two/shared-model']} value="one/shared-model" disabled={false} onPick={value=>{selected=value;}}/></LocaleProvider>));
await act(async()=>(document.querySelector('.settings-model-picker .settings-select') as HTMLButtonElement).click());
const options=Array.from(document.querySelectorAll<HTMLButtonElement>('[role="option"]'));
assert.equal(options.length,2);
assert.deepEqual(Array.from(document.querySelectorAll('.settings-select-menu__group')).map(n=>n.textContent),['Connection one','Connection two']);
assert.equal(options[0].querySelector('small'),null);
await act(async()=>options[1].click());
assert.equal(selected,'two/shared-model');
await act(async()=>root.unmount());
console.log('PASS: same model in independent connections retains identity and selection');
