import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import type { ProviderView } from "../lib/types";

const dom = new JSDOM('<div id="root"></div>', {url:"http://localhost",pretendToBeVisual:true});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,Node:dom.window.Node,HTMLElement:dom.window.HTMLElement,requestAnimationFrame:dom.window.requestAnimationFrame.bind(dom.window),cancelAnimationFrame:dom.window.cancelAnimationFrame.bind(dom.window),IS_REACT_ACT_ENVIRONMENT:true});
const {createRoot} = await import("react-dom/client");
const {ProviderEditor} = await import("../components/SettingsPanel");
const {LocaleProvider} = await import("../lib/i18n");
const root = createRoot(document.getElementById("root")!);
const initial = {name:"custom",kind:"openai",baseUrl:"https://example.com/v1",models:["chat"],default:"chat",apiKeyEnv:"OLD_REF",keySet:true,added:true,builtIn:false,visionModels:[],supportedEfforts:[],modelsUrl:"",balanceUrl:"",contextWindow:0} as ProviderView;
const pending: {resolve:()=>void;reject:(e:Error)=>void;provider:ProviderView;key?:string}[]=[];
const onSave = (provider:ProviderView,key?:string) => new Promise<void>((resolve,reject)=>pending.push({resolve,reject,provider,key}));
const render = async (value=initial) => act(async()=>root.render(<LocaleProvider><ProviderEditor initial={value} kinds={["openai"]} busy={false} onCancel={()=>{}} onSave={onSave}/></LocaleProvider>));
const save = () => document.querySelector<HTMLButtonElement>(".provider-editor-footer .btn--primary")!;
const url = () => document.querySelector<HTMLInputElement>(".provider-url-input")!;
const key = () => document.querySelector<HTMLInputElement>('input[type="password"]')!;
async function change(input:HTMLInputElement,value:string) {
  await act(async()=>{Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value")!.set!.call(input,value);input.dispatchEvent(new window.Event("input",{bubbles:true}));});
}
await render();
await change(key(),"first-key");
await act(async()=>save().click());
assert.equal(pending.length,1);
await change(url(),"https://new.example/v1/chat/completions");
await change(key(),"newer-key");
await act(async()=>pending[0].resolve());
await render({...initial,apiKeyEnv:"NEW_SERVER_OWNED_REF"});
assert.equal(url().value,"https://new.example/v1/chat/completions","save readback preserves a newer URL draft");
assert.equal(key().value,"newer-key","old success does not clear a newer key");
assert.equal(save().disabled,false,"newer edits still need saving");
await act(async()=>save().click());
await act(async()=>pending[1].resolve());
assert.equal(key().value,"","current saved key is cleared");
assert.equal(save().disabled,true,"only the committed draft becomes clean");
await change(url(),"https://failure.example/v1/chat/completions");
await act(async()=>save().click());
await act(async()=>pending[2].reject(new Error("injected persistence failure")));
assert.equal(save().disabled,false,"failure retains unsaved changes");
assert.ok(document.body.textContent?.includes("injected persistence failure"));
await act(async()=>save().click());
await change(url(),"https://latest.example/v1/chat/completions");
await act(async()=>save().click());
await act(async()=>pending[4].resolve());
await act(async()=>pending[3].reject(new Error("stale failure must disappear")));
assert.equal(save().disabled,true,"stale completion cannot dirty the newer committed draft");
assert.ok(!document.body.textContent?.includes("stale failure must disappear"));
await act(async()=>root.unmount());
console.log("PASS: controlled save success/failure, newer URL/key drafts, readback and out-of-order completion");
