import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import * as memory from "../lib/workspaceViewMemory";
import * as legacy from "../lib/workspaceTreeMemory";

const dom = new JSDOM("", { url: "http://localhost/" });
Object.assign(globalThis, { window: dom.window, localStorage: dom.window.localStorage });
legacy.resetWorkspaceTreeMemoryForTests();
legacy.rememberWorkspaceTreeState("A", { selectedFilePath: "legacy.ts", openDirs: new Set(["", "src"]), recentPaths: ["legacy.ts"], dockTreeWidth: 440 });
const a = memory.workspaceViewMemoryKey("A", "first", true);
const b = memory.workspaceViewMemoryKey("A", "second");
const c = memory.workspaceViewMemoryKey("B", "first", true);
assert.equal(memory.readWorkspaceTreeMemory(a)?.selectedFilePath, "legacy.ts");
assert.equal(memory.readWorkspaceTreeMemory(b)?.selectedFilePath, null);
assert.equal(memory.readWorkspaceTreeMemory(c)?.selectedFilePath, null);
memory.rememberWorkspaceTreeState(a, { selectedFilePath: "a.ts", openTabs: ["a.ts", "a2.ts"], filter: "src", openDirs: new Set(["", "src/a"]), recentPaths: ["a.ts"] });
memory.rememberWorkspaceTreeScroll(a, 320);
memory.rememberWorkspaceTreeState(b, { selectedFilePath: "b.ts", openTabs: ["b.ts"], filter: "docs", openDirs: new Set(["", "docs"]), dockTreeWidth: 480 });
memory.rememberWorkspaceTreeScroll(b, 170);
memory.flushWorkspaceTreeMemory();
memory.reloadWorkspaceViewMemoryForTests();
assert.equal(memory.readWorkspaceTreeMemory(a)?.selectedFilePath, "a.ts");
assert.deepEqual(memory.readWorkspaceTreeMemory(a)?.openTabs, ["a.ts", "a2.ts"]);
assert.equal(memory.readWorkspaceTreeMemory(a)?.filter, "src");
assert.equal(memory.readWorkspaceTreeMemory(a)?.scrollTop, 320);
assert.equal(memory.readWorkspaceTreeMemory(b)?.selectedFilePath, "b.ts");
assert.equal(memory.readWorkspaceTreeMemory(b)?.filter, "docs");
assert.equal(memory.readWorkspaceTreeMemory(b)?.scrollTop, 170);
assert.deepEqual(memory.readWorkspaceTreeMemory(b)?.recentPaths, ["a.ts"]);
assert.equal(memory.readWorkspaceTreeMemory(a)?.dockTreeWidth, 480);
assert.equal(memory.readWorkspaceTreeMemory(c)?.selectedFilePath, null);
assert.equal(memory.readWorkspaceTreeMemory(memory.workspaceViewMemoryKey("A", "new-first", true))?.selectedFilePath, null, "legacy seeds only once");
assert.equal(legacy.readWorkspaceTreeMemory("A")?.selectedFilePath, "legacy.ts", "view writes preserve legacy browsing state for downgrade");
const persisted = JSON.parse(localStorage.getItem("reasonix.workspaceViews.v1")!);
assert(!("recentPaths" in persisted.projects.A.views.first));
assert(!("dockTreeWidth" in persisted.projects.A.views.first));
const future = JSON.stringify({ version: 9, data: "future-writer-owned" });
localStorage.setItem("reasonix.workspaceViews.v1", future);
memory.reloadWorkspaceViewMemoryForTests();
memory.rememberWorkspaceTreeState(a, { selectedFilePath: "temporary.ts" });
assert.equal(localStorage.getItem("reasonix.workspaceViews.v1"), future, "unknown versions remain untouched");
dom.window.close();
console.log("PASS per-view navigation, project history/geometry, restart and legacy/future compatibility");
